from .genres import render_genre_statistic_view
from .authors import render_author_statistic_view
from .books_read import render_read_book_statistic_view
from .general import render_general_statistic_view
